spring:
  datasource:
    username: root
    password: ldp013866
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 整合mybatis
mybatis:
  type-aliases-package: com.hand.pojo
  mapper-locations: classpath:mapper/*.xml
